on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH and Deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ env.KNOWN_HOSTS }}
          server-dir: public_html/
